routes/web.php
Route::get('guide/ragnarok-mobile-all-cooking-recipes', function () {
    return redirect('guide/cooking-recipes');
});

Route::get('jobs', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.index', compact('guides', 'events'));
});

Route::get('thief', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.thief', compact('guides', 'events'));
});

Route::get('assassin', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.assassin', compact('guides', 'events'));
});

Route::get('assassin-cross', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.assassin-cross', compact('guides', 'events'));
});

Route::get('merchant', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.merchant', compact('guides', 'events'));
});

Route::get('blacksmith', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.blacksmith', compact('guides', 'events'));
});

Route::get('whitesmith', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.whitesmith', compact('guides', 'events'));
});

Route::get('rogue', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.rogue', compact('guides', 'events'));
});

Route::get('stalker', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.stalker', compact('guides', 'events'));
});

Route::get('acolyte', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.acolyte', compact('guides', 'events'));
});

Route::get('priest', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.priest', compact('guides', 'events'));
});

Route::get('high-priest', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.high-priest', compact('guides', 'events'));
});

Route::get('monk', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.monk', compact('guides', 'events'));
});

Route::get('champion', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.champion', compact('guides', 'events'));
});

Route::get('archer', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.archer', compact('guides', 'events'));
});

Route::get('hunter', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.hunter', compact('guides', 'events'));
});

Route::get('sniper', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.sniper', compact('guides', 'events'));
});

Route::get('alchemist', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.alchemist', compact('guides', 'events'));
});

Route::get('creator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.creator', compact('guides', 'events'));
});

Route::get('mage', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.magician', compact('guides', 'events'));
});

Route::get('wizard', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.wizard', compact('guides', 'events'));
});

Route::get('high-wizard', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.high-wizard', compact('guides', 'events'));
});

Route::get('swordsman', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.swordsman', compact('guides', 'events'));
});

Route::get('knight', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.knight', compact('guides', 'events'));
});

Route::get('lord-knight', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.lord-knight', compact('guides', 'events'));
});

Route::get('crusader', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.crusader', compact('guides', 'events'));
});

Route::get('paladin', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.jobs.paladin', compact('guides', 'events'));
});

Route::get('skill-simulator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.skill-simulator', compact('guides', 'events'));
});

Route::get('priest-skill-simulator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.priest-skill-simulator', compact('guides', 'events'));
});

Route::get('monk-skill-simulator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.monk-skill-simulator', compact('guides', 'events'));
});

Route::get('knight-skill-simulator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.knight-skill-simulator', compact('guides', 'events'));
});

Route::get('crusader-skill-simulator', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.crusader-skill-simulator', compact('guides', 'events'));
});

Route::get('valhalla-ruins', function () {
	$guides = Blog::where('category', 'Guide')->orderBy('created_at', 'desc')->get();
    $events = Event::all();
    return view('frontend.pages.valhalla-ruins', compact('guides', 'events'));
});

Route::get('/endless-tower', 'PageController@endlessTower');

Route::get('/monsters', 'FrontendController@monsters');

Route::get('/monster/{slug}', 'FrontendController@showMonster');

Route::get('/monsters/{name}', 'FrontendController@monsterFilter');

Route::get('/items', 'FrontendController@items');

Route::get('/item/{slug}', 'FrontendController@showItem');

Route::get('/access/{slug}', 'FrontendController@dropItem');

Route::get('/cards', 'FrontendController@cards');

Route::get('/card/{slug}', 'FrontendController@showCard');

Route::get('/map/{slug}', 'FrontendController@showMap');

Route::get('/maps', 'FrontendController@allMaps');

Route::get('/guides', 'FrontendController@guides');

Route::get('/guide/{slug}', 'FrontendController@showGuide');

Route::get('/quests', 'FrontendController@quests');

Route::get('/quest/{slug}', 'FrontendController@showQuest');

Route::get('/search', 'FrontendController@search');

Auth::routes();

Route::group(['middleware' => ['auth']], function() {

	Route::get('admin', 'HomeController@index');

	Route::resource('admin/blogs', 'BlogController');
	Route::get('/admin-blogs', 'BlogController@search');

	Route::resource('admin/users', 'UserController');

	Route::resource('admin/monsters', 'MonsterController');
	Route::get('/admin-monsters', 'MonsterController@search');

	Route::resource('admin/items', 'ItemController');
	Route::get('/admin-items', 'ItemController@search');
    Route::get('admin/items/tier/{id}', 'ItemController@tier');
    Route::post('admin/items/tier/save/{id}', 'ItemController@saveTier');

	Route::resource('admin/cards', 'CardController');
	Route::get('/admin-cards', 'CardController@search');

	Route::resource('admin/events', 'EventController');

	Route::resource('admin/drops', 'DropController');

	Route::resource('admin/types', 'TypeController');

	Route::resource('admin/zones', 'ZoneController');

	Route::resource('admin/characters', 'CharacterController');

	Route::resource('admin/races', 'RaceController');

	Route::resource('admin/item-types', 'ItemTypeController');

	Route::resource('admin/sizes', 'SizeController');

	Route::resource('admin/maps', 'MapController');

	Route::resource('admin/elements', 'ElementController');

    Route::resource('admin/jobs', 'JobController');

    Route::resource('admin/skills', 'SkillController');

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Type;
use Illuminate\Http\Request;
use Toast;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = Type::all();

        return view('admin.types.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.types.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();

        $types = Type::create($inputs);

        Toast::success('Zone added', 'Success');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit(Type $type)
    {
        return view('admin.types.update', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Type $type)
    {
        $inputs = $request->all();

        $type->update($request->all());

        Toast::success('Type updated', 'Success');

        return redirect('admin/types');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy(Type $type)
    {
        $type->delete();

        Toast::success('Type Deleted', 'Success');

        return redirect('admin/types');
    }
}

resources/views/admin/types/add.blade.php
@extends('layouts.master')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      	<h1>Add Type<small></small></h1>
    </section>

    <!-- Main content -->
    <section class="content">
      	<div class="row">
        <!-- left column -->
        	<div class="col-md-6">
	          	<div class="box box-primary">
		            <!-- form start -->
		            {!! Form::open([ 'route' => 'types.store', 'enctype' => 'multipart/form-data'])!!}
	              	<div class="box-body">
		                <div class="form-group">
		                  <label for="name">Name</label>
		                  <input type="text" class="form-control" name="name" placeholder="Enter name" required>
		                </div>
	              	</div>                 
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                  {!! Form::close() !!}
	          	</div>
		      </div>
      	</div>
    </section>
    @include('admin.errors.error')
    @include('admin.messages.message')
@endsection

@section('footer')
<script>
  $(function () {
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5();
    $('.select2').select2()
  })
</script>
@endsection

resources/views/admin/types/index.blade.php
@extends('layouts.master')
@section('content')
	<!-- Content Header (Page header) -->
	<section class="content-header">              
		<div class="pull-right">
			<a href="{{ url('admin/types/create') }}" type="button" class="btn bg-purple"><i class="fa fa-plus"></i> Add Type</a>
		</div>
		<h1>Type<small>List of types</small></h1>
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header "></div>
					<div class="box-body">
						@include('admin.types.table')
					</div>
					@include('admin.errors.error')
					@include('admin.messages.message')
				</div>
			</div>
		</div>
	</section>
	@include('admin.modals.modal')
@endsection

resources/views/admin/types/show.blade.php
show.blade.php

resources/views/admin/types/table.blade.php
<table id="example1" class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@php $count = 1 @endphp
		@foreach ($types as $type)
		<tr>
			<td>{{ $count }}</td>
			<td>{{ $type->name }}</td>
			<td>
			  <div class="timeline-footer">
			    <a class="btn btn-primary btn-xs" href="{{ route('types.show', $type->id) }}">View</a>
			    <a class="btn btn-primary btn-xs" href="{{ route('types.edit', $type->id) }}">Edit</a>
			    {!! Form::model($type ,['route' => ['types.destroy', $type->id], 'method' => 'DELETE', 'style' => 'display: inline-block', 'class' => 'form-inline form-delete']) !!}
			    <button type="submit" class="btn btn-danger btn-xs">Delete</button>
			    {!! Form::close() !!}
			  </div>
			</td>
		</tr>
		@php $count++ @endphp
		@endforeach
	</tbody>
	<tfoot>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Action</th>
		</tr>
	</tfoot>
</table>

resources/views/admin/types/update.blade.php
@extends('layouts.master')
@section('content')
      <!-- Content Header (Page header) -->
      <section class="content-header">
            <h1>Update Type<small></small></h1>
      </section>

      <!-- Main content -->
      <section class="content">
            <div class="row">
                  <!-- left column -->
                  <div class="col-md-6">
                        <div class="box box-primary">
                            <!-- form start -->
                            {!! Form::model($type,['route' => ['types.update', $type->id], 'method' => 'PATCH', 'enctype' => 'multipart/form-data']) !!}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter name" value="{{ $type->name }}">
                                </div>
                            </div>                    
                            <div class="box-footer">
                              <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            {!! Form::close() !!}
                        </div>
                  </div>
            </div>
      </section>
              @include('admin.errors.error')
              @include('admin.messages.message')
      @endsection

      @section('footer')
      <script>
      $(function () {
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5();
      $('.select2').select2()
      })
      </script>
@endsection